
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'medalion_databricks'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'medalion_databricks'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

flags:
  use_managed_iceberg: true
  use_concurrent_microbatch: true
  use_materialization_v2: true

seeds:
  +enabled: true
  +tags: seed
  +database: "{{ target.database }}"
  +schema: seeds

models:
  medalion_databricks:
    staging:
      +enabled: true
      +tags: staging
      +database: dbt_bara_project
      +schema: staging
      +full_refresh: false
      +materialized: view
      +contract:
        enforced: true
    Intermediate:
      +enabled: true
      +tags: intermediate
      +database: dbt_bara_project
      +schema: intermediate
      +full_refresh: false
      +materialized: ephemeral
      +contract:
        enforced: true
    marts:
      dimension_table:
        +enabled: true
        +tags: marts_dimension
        +database: dbt_bara_project
        +schema: marts
        +full_refresh: false
        +materialized: table
        +contract:
          enforced: true
      fact_table:
        +enabled: true
        +tags: marts_fact
        +database: dbt_bara_project
        +schema: marts
        +full_refresh: true
        +materialized: table
        +contract:
          enforced: true