# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "medalion_databricks"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "medalion_databricks"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

flags:
  # Enables native Iceberg table format support on Databricks
  use_managed_iceberg: true
  # Allows concurrent execution of microbatches for faster streaming processing
  use_concurrent_microbatch: true
  # Uses the newer, more performant materialization strategy for Databricks adapters
  use_materialization_v2: true

seeds:
  +enabled: true
  +tags: seed
  +database: "{{ target.database }}"
  +schema: seeds

models:
  medalion_databricks:
    staging:
      +enabled: true
      +tags: staging
      +database: dbt_bara_project
      +schema: staging
      +full_refresh: false
      +materialized: view
      # Enforces model contracts, ensuring the data matches the defined schema and types
      +contract:
        enforced: true
    Intermediate:
      +enabled: true
      +tags: intermediate
      +database: dbt_bara_project
      +schema: intermediate
      +full_refresh: false
      # Ephemeral models are not built into the database; instead, their code is interpolated into downstream models like a CTE
      +materialized: ephemeral
      # Enforces model contracts, ensuring the data matches the defined schema and types
      +contract:
        enforced: true
    marts:
      dimension_table:
        +enabled: true
        +tags: marts_dimension
        +database: dbt_bara_project
        +schema: marts
        +full_refresh: false
        +materialized: table
        # Enforces model contracts, ensuring the data matches the defined schema and types
        +contract:
          enforced: true
      fact_table:
        +enabled: true
        +tags: marts_fact
        +database: dbt_bara_project
        +schema: marts
        # Forces a full rebuild of the table on every run instead of an incremental update
        +full_refresh: true
        +materialized: table
        # Enforces model contracts, ensuring the data matches the defined schema and types
        +contract:
          enforced: true
